const mongoose = require("mongoose");
const { Schema } = mongoose;

const MetaDataSchema = new Schema({
  exchange: String,
  category: String,
  sector: String,
  marketCap: Number,
  peRatio: Number,
  eps: Number,
  earningYield: Number,
  tradingBasis: String,
  dividendRate: Number,
  dividendYield: Number,
  frankedPct: Number,
  issue: String,
  return1m: Number,
  return3m: Number,
  return6m: Number,
  return12m: Number,
});

const IpoSchema = new Schema({
  $date: Date,
});

const CompanyProfileSchema = new Schema({
  _t: String,
  address: String,
  city: String,
  country: String,
  currency: String,
  cuip: String,
  sedol: String,
  description: String,
  employeeTotal: Number,
  exchange: String,
  group: String,
  gsector: String,
  gsubind: String,
  ipo: String,
  isin: String,
  marketCapitalization: Number,
  naics: String,
  naicsNationalIndustry: String,
  naicsSector: String,
  naicsSubsector: String,
  name: String,
  phone: String,
  shareOutstanding: Number,
  state: String,
  ticker: String,
  weburl: String,
  logo: String,
  finnhubIndustry: String,
});

const StockMetricsSchema = new Schema({
  _10DayAverageTradingVolume: Number,
  _13WeekPriceReturnDaily: Number,
  _26WeekPriceReturnDaily: Number,
  _3MonthADReturnStd: Number,
  _3MonthAverageTradingVolume: Number,
  _52WeekHigh: Number,
  _52WeekHighDate: { $date: Date },
  _52WeekLow: Number,
  _52WeekLowDate: { $date: Date },
  _52WeekPriceReturnDaily: Number,
  _5DayPriceReturnDaily: Number,
  AssetTurnoverAnnual: Number,
  AssetTurnoverTTM: Number,
  Beta: Number,
  BookValuePerShareAnnual: Number,
  BookValuePerShareQuarterly: Number,
  BookValueShareGrowth5Y: Number,
  CapexCagr5Y: Number,
  CashFlowPerShareAnnual: Number,
  CashFlowPerShareQuarterly: Number,
  CashFlowPerShareTTM: Number,
  CashPerSharePerShareAnnual: Number,
  CashPerSharePerShareQuarterly: Number,
  CurrentDividendYieldTTM: Number,
  CurrentEvFreeCashFlowAnnual: Number,
  CurrentEvFreeCashFlowTTM: Number,
  CurrentRatioAnnual: Number,
  CurrentRatioQuarterly: Number,
  DividendGrowthRate5Y: Number,
  DividendPerShareAnnual: Number,
  DividendPerShareTTM: Number,
  DividendYieldIndicatedAnnual: Number,
  DividendsPerShareTTM: Number,
  EbitdPerShareAnnual: Number,
  EbitdPerShareTTM: Number,
  EbitdaCagr5Y: Number,
  EbitdaInterimCagr5Y: Number,
  EnterpriseValue: Number,
  EpsAnnual: Number,
  EpsBasicExclExtraItemsAnnual: Number,
  EpsBasicExclExtraItemsTTM: Number,
  EpsExclExtraItemsAnnual: Number,
  EpsExclExtraItemsTTM: Number,
  EpsGrowth3Y: Number,
  EpsGrowth5Y: Number,
  EpsGrowthQuarterlyYoy: Number,
  EpsGrowthTTMYoy: Number,
  EpsInclExtraItemsAnnual: Number,
  EpsInclExtraItemsTTM: Number,
  EpsNormalizedAnnual: Number,
  EpsTTM: Number,
  FocfCagr5Y: Number,
  GrossMargin5Y: Number,
  GrossMarginAnnual: Number,
  GrossMarginTTM: Number,
  InventoryTurnoverAnnual: Number,
  InventoryTurnoverTTM: Number,
  LongTermDebtEquityAnnual: Number,
  LongTermDebtEquityQuarterly: Number,
  MarketCapitalization: Number,
  MonthToDatePriceReturnDaily: Number,
  NetIncomeEmployeeAnnual: Number,
  NetIncomeEmployeeTTM: Number,
  NetInterestCoverageAnnual: Number,
  NetInterestCoverageTTM: Number,
  NetMarginGrowth5Y: Number,
  NetProfitMargin5Y: Number,
  NetProfitMarginAnnual: Number,
  NetProfitMarginTTM: Number,
  OperatingMargin5Y: Number,
  OperatingMarginAnnual: Number,
  OperatingMarginTTM: Number,
  PayoutRatioAnnual: Number,
  PayoutRatioTTM: Number,
  PbAnnual: Number,
  PbQuarterly: Number,
  PcfShareAnnual: Number,
  PcfShareTTM: Number,
  PeAnnual: Number,
  PeBasicExclExtraTTM: Number,
  PeExclExtraAnnual: Number,
  PeExclExtraTTM: Number,
  PeInclExtraTTM: Number,
  PeNormalizedAnnual: Number,
  PeTTM: Number,
  PfcfShareAnnual: Number,
  PfcfShareTTM: Number,
  PretaxMargin5Y: Number,
  PretaxMarginAnnual: Number,
  PretaxMarginTTM: Number,
  PriceRelativeToSP50013Week: Number,
  PriceRelativeToSP50026Week: Number,
  PriceRelativeToSP5004Week: Number,
  PriceRelativeToSP50052Week: Number,
  PriceRelativeToSP500Ytd: Number,
  PsAnnual: Number,
  PsTTM: Number,
  PtbvAnnual: Number,
  PtbvQuarterly: Number,
  QuickRatioAnnual: Number,
  QuickRatioQuarterly: Number,
  ReceivablesTurnoverAnnual: Number,
  ReceivablesTurnoverTTM: Number,
  RevenueEmployeeAnnual: Number,
  RevenueEmployeeTTM: Number,
  RevenueGrowth3Y: Number,
  RevenueGrowth5Y: Number,
  RevenueGrowthQuarterlyYoy: Number,
  RevenueGrowthTTMYoy: Number,
  RevenuePerShareAnnual: Number,
  RevenuePerShareTTM: Number,
  RevenueShareGrowth5Y: Number,
  Roa5Y: Number,
  RoaRfy: Number,
  RoaTTM: Number,
  Roe5Y: Number,
  RoeRfy: Number,
  RoeTTM: Number,
  Roi5Y: Number,
  RoiAnnual: Number,
  RoiTTM: Number,
  TangibleBookValuePerShareAnnual: Number,
  TangibleBookValuePerShareQuarterly: Number,
  TbvCagr5Y: Number,
  TotalDebtTotalEquityAnnual: Number,
  TotalDebtTotalEquityQuarterly: Number,
  YearToDatePriceReturnDaily: Number,
});

const DataSchema = new Schema({
  _id: String,
  type: String,
  open: Number,
  high: Number,
  low: Number,
  close: Number,
  volume: Number,
  date: { $date: Date },
  value: Number,
});

const SymbolDataSchema = new Schema({
  symbol: String,
  companyName: String,
  assetID: String,
  timeFrame: String,
  metaData: MetaDataSchema,
  companyProfile: CompanyProfileSchema,
  stockMetrics: StockMetricsSchema,
  data: [DataSchema],
  weeklyData: [DataSchema],
  monthlyData: [DataSchema],
  isWeekUpdated: Boolean,
  isMonthUpdated: Boolean,
  classificationInfo: String,
});

const SymbolsData = mongoose.model(
  "SymbolsData",
  SymbolDataSchema,
  "SymbolsData"
);
module.exports = SymbolsData;
